### ISSUE TITLE
Indigo not working

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#29]
Currently neither master branch and cutting edge branch are not working.

**Comment by larjohn** [comment]
Do you need any help on this? What is the error?

What is the URL of the application?

**Comment by schmaluk** [comment]
Hello @larjohn 
the URL is: http://eis.openbudgets.iais.fraunhofer.de/indigo
I use this https://raw.githubusercontent.com/openbudgets/integration/master/docker-config/indigo/environment.ts
and this https://raw.githubusercontent.com/openbudgets/integration/master/docker-config/indigo/index.html
for defining a basePath.
I see this in the logs:
```
indigo_1                | ** NG Live Development Server is running on http://0.0.0.0:80 **
indigo_1                | Hash: 61caac94baa674e8ae0e
indigo_1                | Time: 26578ms
indigo_1                | chunk    {0} styles.bundle.js, styles.bundle.js.map (styles) 124 kB {3} [initial] [rendered]
indigo_1                | chunk    {1} main.bundle.js, main.bundle.js.map (main) 493 kB {2} [initial] [rendered]
indigo_1                | chunk    {2} vendor.bundle.js, vendor.bundle.js.map (vendor) 6.25 MB [initial] [rendered]
indigo_1                | chunk    {3} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
indigo_1                | 
indigo_1                | WARNING in ./~/@angular/router/src/router_module.js
indigo_1                | 304:51-71 "export 'LOCATION_INITIALIZED' was not found in '@angular/common'
indigo_1                | 
indigo_1                | ERROR in /app/src/app/components/analysis/visualizations/lineChart.ts (167,14): Argument of type '[string, string] | [undefined, undefined]' is not assignable to parameter of type '(number | { valueOf(): number; })[]'.
indigo_1                |   Type '[string, string]' is not assignable to type '(number | { valueOf(): number; })[]'.
indigo_1                |     Types of property 'push' are incompatible.
indigo_1                |       Type '(...items: string[]) => number' is not assignable to type '(...items: (number | { valueOf(): number; })[]) => number'.
indigo_1                |         Types of parameters 'items' and 'items' are incompatible.
indigo_1                |           Type 'number | { valueOf(): number; }' is not assignable to type 'string'.
indigo_1                |             Type 'number' is not assignable to type 'string'.)
indigo_1                | 
indigo_1                | ERROR in /app/src/app/components/analysis/visualizations/acfChart.ts (110,21): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.)
indigo_1                | 
indigo_1                | ERROR in /app/src/app/components/analysis/visualizations/scatterPlot.ts (149,14): Argument of type '[string, string] | [undefined, undefined]' is not assignable to parameter of type '(number | { valueOf(): number; })[]'.
indigo_1                |   Type '[string, string]' is not assignable to type '(number | { valueOf(): number; })[]'.)
indigo_1                | /app/src/app/components/analysis/visualizations/scatterPlot.ts (152,14): Argument of type 'string[]' is not assignable to parameter of type '(number | { valueOf(): number; })[]'.
indigo_1                |   Type 'string' is not assignable to type 'number | { valueOf(): number; }'.)
indigo_1                | 
indigo_1                | ERROR in /app/src/app/components/analysis/visualizations/boxPlot.ts (122,16): Argument of type 'string[]' is not assignable to parameter of type '(number | { valueOf(): number; })[]'.
indigo_1                |   Type 'string' is not assignable to type 'number | { valueOf(): number; }'.)
indigo_1                | 
indigo_1                | ERROR in /app/src/app/components/analysis/visualizations/histogram.ts (130,14): Argument of type 'string[]' is not assignable to parameter of type '(number | { valueOf(): number; })[]'.
indigo_1                |   Type 'string' is not assignable to type 'number | { valueOf(): number; }'.)
indigo_1                | /app/src/app/components/analysis/visualizations/histogram.ts (132,14): Argument of type 'string[]' is not assignable to parameter of type '(number | { valueOf(): number; })[]'.
indigo_1                |   Type 'string' is not assignable to type 'number | { valueOf(): number; }'.)
indigo_1                | webpack: Failed to compile.
```

**Comment by schmaluk** [comment]
It seems that the basePath is not /indigo. Within the Indigo container I get the the Indigo website via 
```
curl localhost:80
```
But it should be:
```
curl localhost:80/indigo
```

**Comment by larjohn** [comment]
It should now work. There were some dependency versioning issues (typical with angular & typescript).

**Comment by schmaluk** [comment]
Im getting this with the cutting edge branch:
```
indigo_1                | ERROR in ./src/main.ts
indigo_1                | Module build failed: TypeError: Cannot read property 'newLine' of undefined
indigo_1                |     at Object.getNewLineCharacter (/app/node_modules/typescript/lib/typescript.js:8057:20)
indigo_1                |     at Object.createCompilerHost (/app/node_modules/typescript/lib/typescript.js:44974:26)
indigo_1                |     at Object.ngcLoader (/app/node_modules/@ngtools/webpack/src/loader.js:338:33)
indigo_1                |  @ multi webpack-dev-server/client?http://0.0.0.0:80 ./src/main.ts
indigo_1                | webpack: Failed to compile.
```
Also it seems to be necessary to adapt the angular-cli.json to:
```
      "environmentSource":"environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
```
This is my configuration: https://github.com/openbudgets/integration/tree/master/docker-config/indigo
There is another internal testing review this Wednesday. It would be great if we'll be able to test the new version of Indigo.
Thank you.

**Comment by larjohn** [comment]
Can I try this at a live server, from command line? This sounds like older remains of npm module are preventing it to run correctly.

**Comment by schmaluk** [comment]
Hi, thanks. I removed older version & updated angular-cli. Now Im seeing this:
```
# ~/obeu_infrastructure2/docker-config/indigo$ docker run -ti indigo /bin/sh
# /start.sh
** NG Live Development Server is running on http://0.0.0.0:80 **
Hash: 6e65d712612fcb8c3e7f                                                                 
Time: 23266ms
chunk    {0} main.bundle.js, main.bundle.js.map (main) 402 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.js.map (styles) 30.5 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.js.map (vendor) 6.53 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in /app/src/app/components/cube/analytics/cube-analytics-detail.ts (12,30): Module '"/app/node_modules/@angular/material/index"' has no exported member 'MdInput'.)

ERROR in /app/src/app/components/analysis/visualizations/lineChart.ts (167,14): Argument of type '[string, string] | [undefined, undefined]' is not assignable to parameter of type '(number | { valueOf(): number; })[]'.
  Type '[string, string]' is not assignable to type '(number | { valueOf(): number; })[]'.
    Types of property 'push' are incompatible.
      Type '(...items: string[]) => number' is not assignable to type '(...items: (number | { valueOf(): number; })[]) => number'.
        Types of parameters 'items' and 'items' are incompatible.
          Type 'number | { valueOf(): number; }' is not assignable to type 'string'.
            Type 'number' is not assignable to type 'string'.)
```
Yes but alternatively you can try to run Indigo within a Docker container since it will run then on the live server as well probably. 
(If I get a working Dockerfile for Indigo, I can also use that one rather the one in the integration-repo.)
* Checkout the integration-repository: https://github.com/openbudgets/integration
* Switch into this directory https://github.com/openbudgets/integration/tree/master/docker-config/indigo i.e ./docker-config/indigo
* Run: docker build -t indigo .
* Run: docker run -ti indigo /bin/sh
* Run from within the container: /start.sh

**Comment by liyakun** [comment]
@larjohn I tested Indigo by accessing it directly through docker container ip address `http://172.17.0.2/#/indigo/,` which seems working correctly. But by accessing "localhost/indigo/" it output the 404 error when accessing "inline.bundle.js". Do you know which part of the configuration probably causes this problem? thanks.

![indigo](https://cloud.githubusercontent.com/assets/7370334/25476896/ec10f522-2b3b-11e7-9310-9e969ca9963c.png)

**Comment by larjohn** [comment]
I havent seen something like that yet. How to reproduce the situation? Is this the case in the Fraunhofer server so that I can check it?

**Comment by liyakun** [comment]
@larjohn My previous comment is not every concrete, I took the docker configurations of Indigo from [integration](https://github.com/openbudgets/integration.git), and run the docker stand alone. The 404 error happens on both Fraunhofer server and local deployment.

**Comment by larjohn** [comment]
@liyakun  I made a couple of changes to the dockerfile and now, locally it seems to be working ok, even the CSS. Can you try it? I am not sure how to try if it is accessible outside.

**Comment by liyakun** [comment]
@larjohn thanks, it seems that the local deployment working now. I will update changes on the server once I have access to it.

**Comment by liyakun** [comment]
@larjohn Indigo is working on the server after your last changes, thanks.
